### ISSUE TITLE
Error while compiling / running tests

### ISSUE THREAD

**Issue by pdincau** [bigardone/phoenix-toggl#3]
Whey I try to compile the app I get this error:

```
== Compilation error on file lib/phoenix_toggl/guardian_serializer.ex ==
** (SyntaxError) lib/phoenix_toggl/guardian_serializer.ex:4: syntax error before: '{'
    (elixir) lib/kernel/parallel_compiler.ex:100: anonymous fn/4 in
Kernel.ParallelCompiler.spawn_compilers/8
```

Thanks!

**Comment by pdincau** [comment]
oh, i see from one of the your other projects that it requires v 1.2
